repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.17.0
    hooks:
      - id: reorder-python-imports
        args: ["--py38-plus"]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        args: [--safe]
