#!/bin/bash
cd $(dirname $(realpath $0))
cd ../

set -v

# run with PreComp mode (default)
n2v --input demo/karate.edg --output demo/karate.emb --verbose

# run with SparseOTF mode
n2v --input demo/karate.edg --output demo/karate.emb --verbose --mode SparseOTF

# run with DenseOTF mode
n2v --input demo/karate.edg --output demo/karate.emb --verbose --mode DenseOTF

# convert and save edgelist as dense matrix
n2v --input demo/karate.edg --output demo/karate.npz --task todense

# run with DenseOTF mode using dense array as input
n2v --input demo/karate.npz --output demo/karate.emb --verbose --mode DenseOTF

# input parameters
n2v --help
